// File generated by FlutterFire CLI / Ledgify configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcilpujLBYHnOUu3YXNRsffeXekbQFtk8',
    appId: '1:656833575476:web:ca8311fc96a58f9781a861',
    messagingSenderId: '656833575476',
    projectId: 'ledgify-9ac70',
    authDomain: 'ledgify-9ac70.firebaseapp.com',
    storageBucket: 'ledgify-9ac70.firebasestorage.app',
    measurementId: 'G-RHKM9J1PKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUPBLCm38TEZQSEB_pz9Y8DDFMpHyg8fw',
    appId: '1:656833575476:android:bcd23f109e317f4881a861',
    messagingSenderId: '656833575476',
    projectId: 'ledgify-9ac70',
    storageBucket: 'ledgify-9ac70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcilpujLBYHnOUu3YXNRsffeXekbQFtk8',
    appId: '1:656833575476:web:ca8311fc96a58f9781a861',
    messagingSenderId: '656833575476',
    projectId: 'ledgify-9ac70',
    storageBucket: 'ledgify-9ac70.firebasestorage.app',
  );
}
